import type { FastifyInstance, FastifyRequest } from 'fastify';
import { emptyQuerySchema, errorResponses, idParamsSchema, marketRefSchema, mutationHeadersSchema, type CreatePaperAccount, type PaperOrderRequest } from '@pineterm/contracts';
import { ApiError } from '../errors.js';
import '../types.js';

const uuid = { type: 'string', format: 'uuid' } as const;
const timestamp = { type: 'integer', minimum: 0 } as const;
const nullableTimestamp = { anyOf: [timestamp, { type: 'null' }] } as const;
const revision = { type: 'integer', minimum: 1 } as const;
const commandDecimal = { type: 'string', $ref: 'DecimalString#', maxLength: 100 } as const;
const money = { $ref: 'DecimalString#' } as const;
const nullableMoney = { anyOf: [money, { type: 'null' }] } as const;
const currency = { type: 'string', minLength: 1, maxLength: 20, pattern: '^[A-Z0-9][A-Z0-9._-]{0,19}$' } as const;
const name = { type: 'string', minLength: 1, maxLength: 100, pattern: '\\S' } as const;
const mode = { type: 'string', enum: ['live', 'replay'] } as const;
const nullableText = { anyOf: [{ type: 'string' }, { type: 'null' }] } as const;
const createAccountSchema = { type: 'object', additionalProperties: false, required: ['name', 'quoteCurrency'], properties: { name, quoteCurrency: currency, initialBalance: commandDecimal, commissionBps: commandDecimal, slippageBps: commandDecimal } } as const;
const accountSchema = { type: 'object', additionalProperties: false, required: ['id', 'name', 'mode', 'quoteCurrency', 'initialBalance', 'cashBalance', 'reservedCash', 'availableCash', 'commissionBps', 'slippageBps', 'revision', 'archivedAt', 'createdAt', 'updatedAt'], properties: { id: uuid, name, mode, quoteCurrency: currency, initialBalance: money, cashBalance: money, reservedCash: money, availableCash: money, commissionBps: money, slippageBps: money, revision, archivedAt: nullableTimestamp, createdAt: timestamp, updatedAt: timestamp } } as const;
const orderProperties = { accountId: uuid, market: marketRefSchema, side: { type: 'string', enum: ['buy', 'sell'] }, type: { type: 'string', enum: ['market', 'limit', 'stop'] }, quantity: commandDecimal, limitPrice: commandDecimal, stopPrice: commandDecimal } as const;
const orderCommandSchema = {
  type: 'object', additionalProperties: false, required: ['accountId', 'market', 'side', 'type', 'quantity'], properties: orderProperties,
  allOf: [
    { if: { properties: { type: { const: 'limit' } } }, then: { required: ['limitPrice'], not: { required: ['stopPrice'] } }, else: { not: { required: ['limitPrice'] } } },
    { if: { properties: { type: { const: 'stop' } } }, then: { required: ['stopPrice'] }, else: { not: { required: ['stopPrice'] } } },
  ],
} as const;
const orderSchema = { type: 'object', additionalProperties: false, required: ['id', 'accountId', 'market', 'side', 'type', 'quantity', 'acceptedSequence', 'reservedCash', 'reservedQuantity', 'state', 'waitingReason', 'acceptedAt', 'completedAt'], properties: { ...orderProperties, quantity: money, limitPrice: money, stopPrice: money, id: uuid, acceptedSequence: revision, reservedCash: money, reservedQuantity: money, state: { type: 'string', enum: ['open', 'filled', 'cancelled', 'rejected'] }, waitingReason: nullableText, acceptedAt: timestamp, completedAt: nullableTimestamp } } as const;
const positionSchema = { type: 'object', additionalProperties: false, required: ['id', 'accountId', 'market', 'quantity', 'reservedQuantity', 'availableQuantity', 'costBasis', 'averageCost', 'realizedPnl', 'unrealizedPnl', 'marketValue', 'quoteObservedAt', 'quoteStatus', 'revision'], properties: { id: uuid, accountId: uuid, market: marketRefSchema, quantity: money, reservedQuantity: money, availableQuantity: money, costBasis: money, averageCost: nullableMoney, realizedPnl: money, unrealizedPnl: nullableMoney, marketValue: nullableMoney, quoteObservedAt: nullableTimestamp, quoteStatus: { type: 'string', enum: ['live', 'stale', 'historical', 'unavailable'] }, revision } } as const;
const fillSchema = { type: 'object', additionalProperties: false, required: ['id', 'orderId', 'accountId', 'market', 'side', 'quantity', 'price', 'fee', 'currency', 'sourceEventId', 'occurredAt', 'createdAt'], properties: { id: uuid, orderId: uuid, accountId: uuid, market: marketRefSchema, side: orderProperties.side, quantity: money, price: money, fee: money, currency, sourceEventId: { type: 'string' }, occurredAt: timestamp, createdAt: timestamp } } as const;
const ledgerSchema = { type: 'object', additionalProperties: false, required: ['id', 'accountId', 'fillId', 'kind', 'cashDelta', 'cashBalance', 'details', 'occurredAt'], properties: { id: uuid, accountId: uuid, fillId: { anyOf: [uuid, { type: 'null' }] }, kind: { type: 'string', enum: ['initial_balance', 'fill', 'reset'] }, cashDelta: money, cashBalance: money, details: { type: 'object', additionalProperties: true }, occurredAt: timestamp } } as const;
const viewSchema = { type: 'object', additionalProperties: false, required: ['account', 'positions', 'orders', 'fills', 'ledger'], properties: { account: accountSchema, positions: { type: 'array', items: positionSchema }, orders: { type: 'array', items: orderSchema }, fills: { type: 'array', items: fillSchema }, ledger: { type: 'array', items: ledgerSchema } } } as const;
const orderResponse = { type: 'object', additionalProperties: false, required: ['order'], properties: { order: orderSchema } } as const;
const accountFilter = { type: 'object', additionalProperties: false, properties: { accountId: uuid } } as const;
async function rejectBody(request: FastifyRequest): Promise<void> { if (request.body !== undefined) throw new ApiError(400, 'INVALID_SCHEMA', 'This operation does not accept a request body.'); }

export async function registerPaperRoutes(app: FastifyInstance): Promise<void> {
  await app.register(async routes => {
    const readConfig = { security: { access: 'data' as const, scopes: ['paper:read' as const] } };
    const tradeConfig = { security: { access: 'data' as const, scopes: ['paper:trade' as const] } };
    const readSecurity: Array<Record<string, readonly string[]>> = [{ adminSession: [] }, { bearerKey: ['paper:read'] }];
    const tradeSecurity: Array<Record<string, readonly string[]>> = [{ adminSession: [], csrfToken: [] }, { bearerKey: ['paper:trade'] }];
    const tags = ['Paper trading'];
    routes.get<{ Querystring: { mode?: 'live' | 'replay' } }>('/api/v1/paper/accounts', { config: readConfig, preValidation: rejectBody, schema: { operationId: 'listPaperAccounts', tags, description: 'Lists live and replay accounts, including archived accounts whose complete audit histories remain readable.', security: readSecurity, querystring: { type: 'object', additionalProperties: false, properties: { mode } }, response: { 200: { type: 'object', additionalProperties: false, required: ['accounts'], properties: { accounts: { type: 'array', items: accountSchema } } }, ...errorResponses } } }, async request => ({ accounts: app.services.paper.listAccounts(request.query.mode) }));
    routes.post<{ Body: CreatePaperAccount }>('/api/v1/paper/accounts', { config: tradeConfig, schema: { operationId: 'createPaperAccount', tags, description: 'Creates a live-mode spot cash account. Currency must exactly match instruments; no leverage, shorts or USD/USDT conversion. Defaults: 10000 initial cash, 10 commission bps, zero slippage bps.', security: tradeSecurity, headers: mutationHeadersSchema, querystring: emptyQuerySchema, body: createAccountSchema, response: { 201: viewSchema, ...errorResponses } } }, async (request, reply) => reply.code(201).send(app.services.paper.createAccount(request.body)));
    routes.get<{ Params: { id: string } }>('/api/v1/paper/accounts/:id', { config: readConfig, preValidation: rejectBody, schema: { operationId: 'getPaperAccount', tags, description: 'Complete account, holdings, orders, fills and ledger. Unrealized values are null without a fresh live mark, or a revealed replay close.', security: readSecurity, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: viewSchema, ...errorResponses } } }, async request => app.services.paper.getAccount(request.params.id));
    routes.post<{ Params: { id: string }; Body: { confirm: true } }>('/api/v1/paper/accounts/:id/reset', { config: { security: { access: 'admin' as const } }, schema: { operationId: 'resetPaperAccount', tags, description: 'Admin-session only. Explicit confirmation cancels open orders, archives the old account and preserves its full ledger, returning a fresh live account ID with the original initial balance and costs. Replay accounts require stop/new session instead.', security: [{ adminSession: [], csrfToken: [] }], headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, body: { type: 'object', additionalProperties: false, required: ['confirm'], properties: { confirm: { type: 'boolean', const: true } } }, response: { 200: viewSchema, ...errorResponses } } }, async request => app.services.paper.resetAccount(request.params.id));
    routes.post<{ Body: PaperOrderRequest }>('/api/v1/paper/orders', { config: tradeConfig, schema: { operationId: 'placePaperOrder', tags, description: 'Reserves cash including costs or owned quantities transactionally. No client execution price is accepted. A live market order requires a fresh reference and fills only on a different fresh observation received after acceptance. Replay uses the frozen server cursor and next raw bar. Identical account-scoped Idempotency-Key/body returns the original order; conflicting reuse returns 409.', security: tradeSecurity, headers: { ...mutationHeadersSchema, required: ['idempotency-key'], properties: { ...mutationHeadersSchema.properties, 'idempotency-key': { type: 'string', minLength: 1, maxLength: 200, pattern: '^[\\x21-\\x7e]+$' } } }, querystring: emptyQuerySchema, body: orderCommandSchema, response: { 201: orderResponse, ...errorResponses } } }, async (request, reply) => reply.code(201).send({ order: await app.services.paper.placeOrder(request.body, request.headers['idempotency-key'] as string) }));
    routes.post<{ Params: { id: string } }>('/api/v1/paper/orders/:id/cancel', { config: tradeConfig, preValidation: rejectBody, schema: { operationId: 'cancelPaperOrder', tags, description: 'Cancels an open order and releases its reservation atomically. Repeating cancellation returns the cancelled order; filled/rejected orders return 409.', security: tradeSecurity, headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: orderResponse, ...errorResponses } } }, async request => ({ order: app.services.paper.cancelOrder(request.params.id) }));
    routes.get<{ Querystring: { accountId?: string } }>('/api/v1/paper/orders', { config: readConfig, preValidation: rejectBody, schema: { operationId: 'listPaperOrders', tags, security: readSecurity, querystring: accountFilter, response: { 200: { type: 'object', additionalProperties: false, required: ['orders'], properties: { orders: { type: 'array', items: orderSchema } } }, ...errorResponses } } }, async request => ({ orders: app.services.paper.listOrders(request.query.accountId) }));
    routes.get<{ Querystring: { accountId?: string } }>('/api/v1/paper/fills', { config: readConfig, preValidation: rejectBody, schema: { operationId: 'listPaperFills', tags, security: readSecurity, querystring: accountFilter, response: { 200: { type: 'object', additionalProperties: false, required: ['fills'], properties: { fills: { type: 'array', items: fillSchema } } }, ...errorResponses } } }, async request => ({ fills: app.services.paper.listFills(request.query.accountId) }));
    routes.get<{ Querystring: { accountId?: string } }>('/api/v1/paper/positions', { config: readConfig, preValidation: rejectBody, schema: { operationId: 'listPaperPositions', tags, security: readSecurity, querystring: accountFilter, response: { 200: { type: 'object', additionalProperties: false, required: ['positions'], properties: { positions: { type: 'array', items: positionSchema } } }, ...errorResponses } } }, async request => ({ positions: await app.services.paper.listPositions(request.query.accountId) }));
  });
}
