import type { FastifyInstance, FastifyRequest } from 'fastify';
import { emptyQuerySchema, errorResponses, idParamsSchema, liveActionSchema, marketRefSchema, mutationHeadersSchema, type ExecutorCommand, type OrderIntentRequest, type SubmitExecutorReport, type UpdateExecutionPolicy, type UpdateExecutor } from '@pineterm/contracts';
import type { ExecutionService } from './ExecutionService.js';
import { ApiError } from '../errors.js';
import '../types.js';

const uuid = { type: 'string', format: 'uuid' } as const;
const timestamp = { type: 'integer', minimum: 0 } as const;
const revision = { type: 'integer', minimum: 1 } as const;
const decimal = { type: 'string', $ref: 'DecimalString#', maxLength: 100 } as const;
const money = { $ref: 'DecimalString#' } as const;
const nullableMoney = { anyOf: [money, { type: 'null' }] } as const;
const nullableTimestamp = { anyOf: [timestamp, { type: 'null' }] } as const;
const nullableUuid = { anyOf: [uuid, { type: 'null' }] } as const;
const text = { type: 'string', minLength: 1, maxLength: 200 } as const;
const nullableText = { anyOf: [{ type: 'string' }, { type: 'null' }] } as const;
const currency = { type: 'string', minLength: 1, maxLength: 20, pattern: '^[A-Z0-9][A-Z0-9._-]{0,19}$' } as const;
const boolean = { type: 'boolean' } as const;
const name = { type: 'string', minLength: 1, maxLength: 100, pattern: '\\S' } as const;
const executorCommand = { type: 'object', additionalProperties: false, required: ['name','enabled'], properties: { name, enabled: boolean } } as const;
const executorSchema = { type: 'object', additionalProperties: false, required: ['id','name','enabled','claimsPausedReason','revision','createdAt','updatedAt','archivedAt'], properties: { id: uuid, name, enabled: boolean, claimsPausedReason: nullableText, revision, createdAt: timestamp, updatedAt: timestamp, archivedAt: nullableTimestamp } } as const;
const allowlist = { type: 'array', minItems: 1, maxItems: 100, items: { type: 'object', additionalProperties: false, required: ['market','sides'], properties: { market: marketRefSchema, sides: { type: 'array', minItems: 1, maxItems: 2, uniqueItems: true, items: { type: 'string', enum: ['buy','sell'] } } } } } as const;
const quoteLimits = { type: 'array', minItems: 1, maxItems: 100, items: { type: 'object', additionalProperties: false, required: ['quoteCurrency','perOrderNotional','rolling24hNotional'], properties: { quoteCurrency: currency, perOrderNotional: decimal, rolling24hNotional: decimal } } } as const;
const policyCommand = { examples: [{ enabled: false, revision: 1 }, { enabled: true, revision: 1, allowlist: [{ market: { provider: 'coinbase', symbol: 'BTC-USD' }, sides: ['buy'] }], quoteLimits: [{ quoteCurrency: 'USD', perOrderNotional: '100', rolling24hNotional: '200' }], maxPending: 1, maxDeviationBps: '100' }], oneOf: [
  { type: 'object', additionalProperties: false, required: ['enabled','revision'], properties: { enabled: { const: false }, revision } },
  { type: 'object', additionalProperties: false, required: ['enabled','revision','allowlist','quoteLimits','maxPending','maxDeviationBps'], properties: { enabled: { const: true }, revision, allowlist, quoteLimits, maxPending: { type: 'integer', minimum: 1, maximum: 1000 }, maxDeviationBps: decimal } },
] } as const;
const policySchema = { type: 'object', additionalProperties: false, required: ['enabled','revision','allowlist','quoteLimits','maxPending','maxDeviationBps','updatedAt'], properties: { enabled: boolean, revision, allowlist: { ...allowlist, minItems: 0 }, quoteLimits: { ...quoteLimits, minItems: 0 }, maxPending: { anyOf: [{ type: 'integer', minimum: 1, maximum: 1000 }, { type: 'null' }] }, maxDeviationBps: nullableMoney, updatedAt: nullableTimestamp } } as const;
const fillSchema = { type: 'object', additionalProperties: false, required: ['externalFillId','quantity','price','fee','currency','time'], properties: { externalFillId: text, quantity: decimal, price: decimal, fee: decimal, currency, time: timestamp } } as const;
const reportProperties = { reportId: text, status: { type: 'string', enum: ['acknowledged','partially_filled','filled','rejected','cancelled','expired','unknown'] }, externalOrderId: text, fills: { type: 'array', maxItems: 1000, items: fillSchema } } as const;
const reportSchema = { type: 'object', additionalProperties: false, required: ['id','intentId','executorId','createdAt','reportId','status','fills'], properties: { ...reportProperties, id: uuid, intentId: uuid, executorId: uuid, createdAt: timestamp } } as const;
const intentSchema = { type: 'object', additionalProperties: false, required: ['id','executorId','market','side','type','quantity','expiresAt','quoteCurrency','referencePrice','referenceObservedAt','maximumDeviationBps','minExecutionPrice','maxExecutionPrice','state','cancelRequested','leaseExpiresAt','externalOrderId','revision','createdAt','updatedAt','sourceEventId','filledQuantity','risk','reports'], properties: {
  ...liveActionSchema.properties, quantity: money, limitPrice: money, id: uuid, expiresAt: timestamp, quoteCurrency: currency, referencePrice: money, referenceObservedAt: timestamp, maximumDeviationBps: money, minExecutionPrice: nullableMoney, maxExecutionPrice: nullableMoney, state: { type: 'string', enum: ['pending','claimed','acknowledged','partially_filled','filled','rejected','cancelled','expired','unknown'] }, cancelRequested: boolean, leaseExpiresAt: nullableTimestamp, externalOrderId: nullableText, revision, createdAt: timestamp, updatedAt: timestamp, sourceEventId: nullableUuid, filledQuantity: money,
  risk: { type: 'object', additionalProperties: false, required: ['requestedNotional','retainedNotional','pendingCapacity','resolvedAt'], properties: { requestedNotional: money, retainedNotional: money, pendingCapacity: boolean, resolvedAt: nullableTimestamp } }, reports: { type: 'array', items: reportSchema },
} } as const;
const intentResponse = { type: 'object', additionalProperties: false, required: ['intent'], properties: { intent: intentSchema } } as const;
const executorResponse = { type: 'object', additionalProperties: false, required: ['executor'], properties: { executor: executorSchema } } as const;
const leaseSchema = { type: 'object', additionalProperties: false, required: ['intent','clientOrderId','leaseToken','leaseExpiresAt','quoteCurrency','quantityStep','tickSize','minExecutionPrice','maxExecutionPrice'], properties: { intent: intentSchema, clientOrderId: uuid, leaseToken: { type: 'string', minLength: 43, maxLength: 43 }, leaseExpiresAt: timestamp, quoteCurrency: currency, quantityStep: money, tickSize: money, minExecutionPrice: nullableMoney, maxExecutionPrice: nullableMoney } } as const;
const controlSchema = { type: 'object', additionalProperties: false, required: ['executorId','executorEnabled','policyEnabled','claimsPausedReason','serverTime','orders'], properties: { executorId: uuid, executorEnabled: boolean, policyEnabled: boolean, claimsPausedReason: nullableText, serverTime: timestamp, orders: { type: 'array', items: leaseSchema } } } as const;
const positionSchema = { type: 'object', additionalProperties: false, required: ['executorId','market','quoteCurrency','netQuantity','boughtQuantity','soldQuantity','boughtNotional','soldNotional','fees','lastFillAt'], properties: { executorId: uuid, market: marketRefSchema, quoteCurrency: currency, netQuantity: money, boughtQuantity: money, soldQuantity: money, boughtNotional: money, soldNotional: money, fees: { type: 'object', additionalProperties: money }, lastFillAt: timestamp } } as const;
async function rejectBody(request: FastifyRequest): Promise<void> { if (request.body !== undefined) throw new ApiError(400, 'INVALID_SCHEMA', 'This operation accepts no request body.'); }

export async function registerExecutionRoutes(app: FastifyInstance, execution: ExecutionService): Promise<void> {
  await app.register(async routes => {
    const admin = { security: { access: 'admin' as const } };
    const read = { security: { access: 'data' as const, scopes: ['live:intent' as const] } };
    const claim = { security: { access: 'data' as const, scopes: ['executor:claim' as const], executorIdParam: 'id' } };
    const report = { security: { access: 'data' as const, scopes: ['executor:report' as const] } };
    const adminSecurity: Array<Record<string, readonly string[]>> = [{ adminSession: [] }]; const adminMutation: Array<Record<string, readonly string[]>> = [{ adminSession: [], csrfToken: [] }];
    const readSecurity: Array<Record<string, readonly string[]>> = [{ adminSession: [] }, { bearerKey: ['live:intent'] }]; const intentSecurity: Array<Record<string, readonly string[]>> = [{ adminSession: [], csrfToken: [] }, { bearerKey: ['live:intent'] }];
    const tags = ['Live execution'];
    routes.get('/api/v1/executors', { config: admin, preValidation: rejectBody, schema: { operationId: 'listExecutors', tags, security: adminSecurity, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['executors'], properties: { executors: { type: 'array', items: executorSchema } } }, ...errorResponses } } }, async () => ({ executors: execution.listExecutors() }));
    routes.get<{ Params: { id: string } }>('/api/v1/executors/:id', { config: admin, preValidation: rejectBody, schema: { operationId: 'getExecutor', tags, security: adminSecurity, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: executorResponse, ...errorResponses } } }, async request => ({ executor: execution.getExecutor(request.params.id) }));
    routes.post<{ Body: ExecutorCommand }>('/api/v1/executors', { config: admin, schema: { operationId: 'createExecutor', tags, security: adminMutation, headers: mutationHeadersSchema, querystring: emptyQuerySchema, body: executorCommand, response: { 201: executorResponse, ...errorResponses } } }, async (request, reply) => reply.code(201).send({ executor: execution.createExecutor(request.body) }));
    routes.put<{ Params: { id: string }; Body: UpdateExecutor }>('/api/v1/executors/:id', { config: admin, schema: { operationId: 'updateExecutor', tags, description: 'Revision-CAS update. Disabling cancels pending unsubmitted intents and requests external cancellation of claimed/accepted/unknown orders.', security: adminMutation, headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, body: { ...executorCommand, required: ['name','enabled','revision'], properties: { ...executorCommand.properties, revision } }, response: { 200: executorResponse, ...errorResponses } } }, async request => ({ executor: execution.updateExecutor(request.params.id, request.body) }));
    routes.delete<{ Params: { id: string } }>('/api/v1/executors/:id', { config: admin, preValidation: rejectBody, schema: { operationId: 'archiveExecutor', tags, description: 'Archives the executor and preserves all intent/report/fill/audit rows. Bound keys retain reconciliation access.', security: adminMutation, headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, response: { 204: { type: 'null' }, ...errorResponses } } }, async (request, reply) => { execution.deleteExecutor(request.params.id); return reply.code(204).send(); });
    routes.get('/api/v1/execution-policy', { config: admin, preValidation: rejectBody, schema: { operationId: 'getExecutionPolicy', tags, security: adminSecurity, querystring: emptyQuerySchema, response: { 200: policySchema, ...errorResponses } } }, async () => execution.getPolicy());
    routes.put<{ Body: UpdateExecutionPolicy }>('/api/v1/execution-policy', { config: admin, schema: { operationId: 'updateExecutionPolicy', tags, description: 'CAS revision. Explicit market/side/currency limits and an enabled executor are mandatory. USD and USDT remain distinct. enabled:false is a kill switch, not an exchange cancellation guarantee.', security: adminMutation, headers: mutationHeadersSchema, querystring: emptyQuerySchema, body: policyCommand, response: { 200: policySchema, ...errorResponses } } }, async request => execution.updatePolicy(request.body));
    routes.post<{ Body: OrderIntentRequest }>('/api/v1/order-intents', { config: read, schema: { operationId: 'createOrderIntent', tags, description: 'Reserves protected worst-case submitted notional and global pending capacity atomically. No client quote, replay/backtest origin or sourceEventId field is accepted. Identical executor/key/body/principal replay returns the original intent even after expiry.', security: intentSecurity, headers: { ...mutationHeadersSchema, required: ['idempotency-key'], properties: { ...mutationHeadersSchema.properties, 'idempotency-key': { type: 'string', minLength: 1, maxLength: 200, pattern: '^[\\x21-\\x7e]+$' } } }, querystring: emptyQuerySchema, body: { ...liveActionSchema, required: [...liveActionSchema.required,'expiresAt'], properties: { ...liveActionSchema.properties, expiresAt: timestamp }, allOf: [{ if: { properties: { type: { const: 'limit' } } }, then: { required: ['limitPrice'] }, else: { not: { required: ['limitPrice'] } } }] }, response: { 202: intentResponse, ...errorResponses } } }, async (request, reply) => reply.code(202).send({ intent: await execution.createIntent(request.body, request.headers['idempotency-key'] as string, request.principal?.kind === 'api-key' ? request.principal.keyId : null) }));
    routes.get('/api/v1/order-intents', { config: read, preValidation: rejectBody, schema: { operationId: 'listOrderIntents', tags, security: readSecurity, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['intents'], properties: { intents: { type: 'array', items: intentSchema } } }, ...errorResponses } } }, async () => ({ intents: execution.listIntents() }));
    routes.get<{ Params: { id: string } }>('/api/v1/order-intents/:id', { config: read, preValidation: rejectBody, schema: { operationId: 'getOrderIntent', tags, description: 'Public intent view excludes lease tokens and encrypted secrets.', security: readSecurity, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: intentResponse, ...errorResponses } } }, async request => ({ intent: execution.getIntent(request.params.id) }));
    routes.post<{ Params: { id: string } }>('/api/v1/order-intents/:id/cancel', { config: read, preValidation: rejectBody, schema: { operationId: 'cancelOrderIntent', tags, description: 'Pending cancels immediately; claimed/acknowledged/partial/unknown remains in that state with cancelRequested until an executor cancellation report.', security: intentSecurity, headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: intentResponse, ...errorResponses } } }, async request => ({ intent: execution.cancelIntent(request.params.id) }));
    routes.post<{ Params: { id: string } }>('/api/v1/executors/:id/claim', { config: claim, preValidation: rejectBody, schema: { operationId: 'claimOrderIntent', tags, description: 'Executor-bound bearer key only, including when an admin session exists. Current policy/fresh quote/precision/expiry/risk rechecked before a single 30-second original encrypted lease. Never redispatch unknown outcomes.', security: [{ bearerKey: ['executor:claim'] }], headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['claim','serverTime'], properties: { claim: { anyOf: [leaseSchema, { type: 'null' }] }, serverTime: timestamp } }, ...errorResponses } } }, async request => { app.security.requireExecutor(request, request.params.id, 'executor:claim'); return execution.claim(request.params.id); });
    routes.get<{ Params: { id: string } }>('/api/v1/executors/:id/control', { config: claim, preValidation: rejectBody, schema: { operationId: 'executorControl', tags, description: 'Bound bearer key only. Recover original lease token and reconcile all claimed/accepted/partial/unknown orders by stable clientOrderId. Recovered rows must never be submitted automatically.', security: [{ bearerKey: ['executor:claim'] }], params: idParamsSchema, querystring: emptyQuerySchema, response: { 200: controlSchema, ...errorResponses } } }, async request => { app.security.requireExecutor(request, request.params.id, 'executor:claim'); return execution.control(request.params.id); });
    routes.post<{ Params: { id: string }; Body: SubmitExecutorReport }>('/api/v1/order-intents/:id/reports', { config: report, schema: { operationId: 'reportExecutorOutcome', tags, description: 'Bound executor:report key and original lease token required, even for late unknown reconciliation. Report and fill IDs deduplicate atomically; conflicting reuse or invalid cumulative fills fail. Duplicate reports return their original response. Fee currencies/rebates are never converted. Acknowledgement alone never means filled.', security: [{ bearerKey: ['executor:report'] }], headers: mutationHeadersSchema, params: idParamsSchema, querystring: emptyQuerySchema, body: { type: 'object', additionalProperties: false, required: ['reportId','status','fills','leaseToken'], properties: { ...reportProperties, leaseToken: { type: 'string', minLength: 1, maxLength: 200 } } }, response: { 200: intentResponse, ...errorResponses } } }, async request => {
      if (request.principal?.kind !== 'api-key' || !request.principal.executorId) throw new ApiError(403, 'EXECUTOR_FORBIDDEN', 'An executor-bound bearer key is required.');
      const executorId = execution.getIntent(request.params.id).executorId;
      app.security.requireExecutor(request, executorId, 'executor:report');
      return { intent: execution.report(request.params.id, executorId, request.body) };
    });
    routes.get('/api/v1/execution-risk', { config: admin, preValidation: rejectBody, schema: { operationId: 'executionRiskUsage', tags, description: 'Conservative submitted-notional risk, not exchange account exposure. Unresolved capacity/notional counts even outside 24 hours; partial fills retain full reservation until terminal proof.', security: adminSecurity, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['usage'], properties: { usage: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['quoteCurrency','rolling24hNotional','unresolvedNotional','pendingIntents'], properties: { quoteCurrency: currency, rolling24hNotional: money, unresolvedNotional: money, pendingIntents: { type: 'integer', minimum: 0 } } } } } }, ...errorResponses } } }, async () => ({ usage: execution.usage() }));
    routes.get('/api/v1/reported-positions', { config: read, preValidation: rejectBody, schema: { operationId: 'externallyReportedPositions', tags, description: 'Net externally reported fills by executor/venue, separate from paper balances and not a complete exchange portfolio.', security: readSecurity, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['positions'], properties: { positions: { type: 'array', items: positionSchema } } }, ...errorResponses } } }, async () => ({ positions: execution.reportedPositions() }));
    routes.get('/api/v1/execution-audit', { config: admin, preValidation: rejectBody, schema: { operationId: 'executionAudit', tags, security: adminSecurity, querystring: emptyQuerySchema, response: { 200: { type: 'object', additionalProperties: false, required: ['entries'], properties: { entries: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id','intentId','executorId','type','details','createdAt'], properties: { id: uuid, intentId: nullableUuid, executorId: nullableUuid, type: { type: 'string' }, details: { type: 'object', additionalProperties: true }, createdAt: timestamp } } } } }, ...errorResponses } } }, async () => ({ entries: execution.audit() }));
  });
}
